### ISSUE TITLE
pinkd silently exits, every time

### ISSUE THREAD

**Issue by ectal** [shaduzlabs/pink-0#4] opened 2017-03-27 14:31 UTC
I've pulled the repo, successfully run the install script, the access point shows up after reboot, everything looks fine, but the demon is never actually running.

If I attempt to start the service:

```
 pink.service - LSB: piNK daemon
   Loaded: loaded (/etc/init.d/pink)
   Active: active (exited) since Mon 2017-03-27 14:11:33 UTC; 54s ago
  Process: 406 ExecStart=/etc/init.d/pink start (code=exited, status=0/SUCCESS)

Mar 27 14:11:33 raspberrypi pink[406]: pinkd: daemon starting
Mar 27 14:11:33 raspberrypi pinkd[412]: daemon starting
Mar 27 14:11:33 raspberrypi systemd[1]: Started LSB: piNK daemon.
```

Then check its status:

```
 pink.service - LSB: piNK daemon
   Loaded: loaded (/etc/init.d/pink)
   Active: active (exited) since Mon 2017-03-27 14:11:33 UTC; 1min 31s ago
  Process: 406 ExecStart=/etc/init.d/pink start (code=exited, status=0/SUCCESS)

Mar 27 14:11:33 raspberrypi pink[406]: pinkd: daemon starting
Mar 27 14:11:33 raspberrypi pinkd[412]: daemon starting
Mar 27 14:11:33 raspberrypi systemd[1]: Started LSB: piNK daemon.
```

Definitely no pinkd process running if I check with ps afterward.

Even with it not running, I still see a lock file:

```
pi@raspberrypi:~ $ ls /var/run/lock/subsys/
pinkd
```

The only "interesting" logging I've been able to find anywhere is in /var/log/daemon.log showing that a restart gets an error because the process isn't found:

```
Mar 27 14:15:33 raspberrypi pink[1084]: pinkd: no process found
Mar 27 14:15:33 raspberrypi systemd[1]: pink.service: control process exited, code=exited status=1
```

Any thoughts? Problem with the hat, maybe? Any unusual place any logging or output might be hiding?

additional info:

* uname -a: Linux raspberrypi 4.4.50+ #970
* Downloaded jessie w/ pixel from: https://www.raspberrypi.org/downloads/raspbian/
* created boot sd using the Mac program Etcher
* Tried the install both before and after an apt-get upgrade

**Comment by hdavid** [comment] 2017-03-27 14:56
i am having the same problem, which seems to be linked to portaudio not finding the default audio ouput. Vincenzo advised me to "check out the develop branch and start the executable manually with the argument "no-daemon", you should see the error 'Could not get audio device'". which i did, confirming the problem.

going to explore tonight, starting with this. 
https://app.assembla.com/wiki/show/portaudio/Platforms_RaspberryPi

the strange part is that i got it work, on a dirty raspberry pi installation before doing "clean install" like you did. so it must be smth linked to libary version, or alsa settings or smth of this sort. i wonder if it would not just work by installing portaudio as a debian package.
i will also whether setting the hdmi ouput forced on does not do a change.

**Comment by ectal** [comment] 2017-03-27 19:38
As far as I can tell, portaudio just wasn't ever installed successfully. Didn't notice any errors when running install.sh. /shrug

I managed to get things working by just downloading portaudio from here:

http://www.portaudio.com/download.html

Just unpacked, did configure, make, sudo make install, and now pinkd gladly runs.

Cheers!

**Comment by hdavid** [comment] 2017-03-27 21:14
confirmed to work ! thanks for the hint :) 
cpu is quite high though on my raspberry pi 3 b. (100% on one core)

**Comment by shaduzlabs** [comment] 2017-03-27 23:21
@ectal thanks indeed for sharing your solution!
Most likely this is due to libsnd2 not being installed when the installer script builds portaudio. I will investigate further and improve the script.

@hdavid wow didn't really pay attention to cpu usage lately! Turned out to be an issue in [nmws](https://github.com/shaduzlabs/nmws), the nanomsg wrapper that provides the web socket connectivity. It should now be fixed on `develop`, but you'll need to update the submodules. 
CPU usage on my pi3 is now <4%.

**Comment by ectal** [comment] 2017-03-28 23:47
@shaduzlabs No problem. And yeah, just installing libasound-dev before running install seems to do the trick, as I discovered after managing to physically destroy an SD card and needing to start over. :)

**Closed as completed** 2017-04-26 02:53 UTC
